{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a115cbfd-6f6b-44bf-a590-4fd47f2fc242",
   "metadata": {},
   "source": [
    "# Steam用户行为分析\r\n",
    "\r\n",
    "## 项目背景\r\n",
    "基于Kaggle Steam-200k数据集，对约12,000名Steam用户的\r\n",
    "购买与游玩行为进行分析，挖掘用户分层特征与平台运营规律。\r\n",
    "数据采集于2017 核## 核心结论\r\n",
    "\r\n",
    "**1. 游戏热度分析**\r\n",
    "Dota2以4,841人购买量和98万小时总游戏时长双榜第一，\r\n",
    "是2016-2017年Steam最具统治力的游戏，购买量是第二名\r\n",
    "Team Fortress 2（2,323人）的2倍以上。平均游戏时长榜中\r\n",
    "Football Manager系列包揽Top4（2014版392h、2012版390.5h、\r\n",
    "2015版315.4h、2013版310.7h），粘性远超其他游戏但购买量\r\n",
    "不突出，说明该系列受众圈小但极度忠诚。购买量高但游玩时长\r\n",
    "极低的游戏（如Deathmatch Classic 0.7h、Half-Life \r\n",
    "Deathmatch Source 0.8h）存在明显体验落差，可玩性存疑。\r\n",
    "\r\n",
    "**2. 用户购买行为**\r\n",
    "45.9%的用户仅购买1款游戏（5,693人），近半数用户属于\r\n",
    "尝鲜型，未形成深度使用习惯。购买20款以上的用户仅占9.8%\r\n",
    "（1,213人），但属于平台最高价值用户群体。购买量最高的\r\n",
    "单一用户达1,075款，属于对所有品类高度接受的重度收藏型玩家。\r\n",
    "用户「最爱游戏」分布中，Dota2以3,971人独占第一，\r\n",
    "是第二名Team Fortress 2（1,033人）的近4倍，\r\n",
    "射击类游戏（CS系列合计约1,170人）整体忠诚度也极高。\r\n",
    "\r\n",
    "**3. 用户分层分析**\r\n",
    "轻度用户（总游玩<10h）占比最高达42%（4,763人）；\r\n",
    "超级用户（>500h）占15.5%（1,757人），人均购买46.6款，\r\n",
    "是轻度用户（2款）的23倍，体现典型二八效应——\r\n",
    "少数核心用户贡献了平台绝大部分消费行为。\r\n",
    "\r\n",
    "**4. 沉默用户分析**\r\n",
    "12,393名购买用户中有1,043人（8.4%）从未启动任何游戏，\r\n",
    "反映了Steam平台特有的「折扣囤游戏」现象，\r\n",
    "促销驱动购买但实际游玩意愿不足。\r\n",
    "\r\n",
    "## 业务建议\r\n",
    "\r\n",
    "- **激活沉默用户：** 针对购买后7天未启动的用户推送游戏\r\n",
    "  新手引导或好友动态通知，将8.4%的沉默用户转化为活跃用户，\r\n",
    "  直接提升DAU。\r\n",
    "\r\n",
    "- **引导轻度用户升层：** 45.9%用户仅购买1款游戏，\r\n",
    "  可在用户首款游戏游玩达5小时后推荐同品类低价游戏或捆绑包，\r\n",
    "  将轻度用户逐步转化为中度用户，提升平台ARPU值。\r\n",
    "\r\n",
    "- **扶持高粘性小众游戏：** Football Manager系列平均游玩\r\n",
    "  超390小时，用户极度忠诚，平台可对此类高粘性小众游戏给予\r\n",
    "  更多首页推荐资源，以圈层化运营构建差异化竞争优势。显引小众游戏给予\r\n",
    "  更多首页推荐资源，吸引圈层用户，构建差异化竞争优势。## 业务建议\r\n",
    "- \r\n",
    "- \r\n",
    "\r\n",
    "## 技术栈\r\n",
    "Python（pandas / matplotlib）| MySQL | Tableau\r\n",
    "\r\n",
    "## 项目结构\r\n",
    "steam-analysis/\r\n",
    "├── data/          原始及清洗后数据\r\n",
    "├── sql/           四个分析模块SQL文件\r\n",
    "├── results/       SQL查询结果\r\n",
    "├── notebooks/     Jupyter分析过程\r\n",
    "├── charts/        Python可视化图表\r\n",
    "└── dashboard/     Tableau Dashboard截图\r\n",
    "\r\n",
    "## 数据说明\r\n",
    "- 数据来源：Kaggle steam-200k\r\n",
    "- 原始数据：200,000条\r\n",
    "- 清洗后：199,293条（删除707条重复记录）\r\n",
    "- 字段：user_id / game_title / behavior / value"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "My Python Environment",
   "language": "python",
   "name": "pytorch"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
